### ISSUE TITLE
Terms from OBI not getting displayed in ontology hierarchy view

### ISSUE THREAD

**Issue by nsuvarnaiari** [EBISPOT/OLS#641] opened 2022-10-05 14:33 UTC
Hi OLS team,

I am trying to access [DNase Hi-C assay](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0003301) OBI:0003301, a term from Ontology for Biomedical Investigations (OBI). I am able to see the term in the results but when I click it to see in the ontology, I get the following error.

![Screen Shot 2022-10-05 at 10 30 09 AM](https://user-images.githubusercontent.com/13201743/194086298-43dfc761-f659-463f-acc9-d1a977400b68.png)
Some other terms also have the same issue eg: micro-C assay, nucleolus-associated domain sequencing assay.

Thanks,
Suvvi

**Comment by serjoshua** [comment] 2022-10-06 08:52
Hello Suvvi,

I already looked into it and this term is most likely affected by the data corruption in OLS we experienced just last month. It is fixed now but to resolve your issue, our team needs to force a data update of OBI to production. We don't do regular data updates in OLS as of the moment but we will prioritize OBI and I will keep you posted regarding any deployment.

If you encounter any term from any ontology behaving the same, please do report it as well. If the issue is confirmed data-related like this one, we will try our best to prioritize an update for that ontology.

**Comment by serjoshua** [comment] 2022-10-20 09:36
Good day Suvvi,

OBI has just been updated in OLS. Upon checking the problematic term, it is resolving now. Feel free to message us if you encounter again any issues. Thanks.

**Closed as completed by serjoshua** 2022-10-20 09:36 UTC

**Comment by nsuvarnaiari** [comment] 2022-10-20 13:42
Thanks @serjoshua !!
