### ISSUE TITLE
Change in baseURI for NCBITaxon?

### ISSUE THREAD

**Issue by jlchang** [EBISPOT/OLS#427] opened 2020-10-15 12:27 UTC
Up until recently (~morning of 10/14) I could use EBI OLS to look up NCBITaxon terms such as NCBITaxon_9606.

My code currently sends the following term lookup which fails with "Resource not found":
https://www.ebi.ac.uk/ols/api/ontologies/ncbitaxon/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCBITAXON_9606

I can see that this query will succeed (NCBITAXON_9606 vs NCBITaxon_9606):
https://www.ebi.ac.uk/ols/api/ontologies/ncbitaxon/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCBITaxon_9606

I had not made any changes to my code for the NCBITaxon term lookup but the lookup behavior changed sometime on 10/14. Your lookup service is very valuable and I would like to understand whether this change in behavior was intended and whether the change is permanent.

Thanks,

Jean

**Comment by jlchang** [comment] 2020-10-15 13:11
Investigating further, it looks like a query to:
`https://www.ebi.ac.uk/ols/api/ontologies/NCBITaxon`
is returning a baseURI of
http://purl.obolibrary.org/obo/NCBITAXON_
Which I am using to generate the term lookup requests. The baseURI may be the root cause of the invalid term lookups I'm experiencing. Can this be investigated?

**Comment by jlchang** [comment] 2020-10-29 15:45
Checking in to see if the invalid baseURI is intended:
http://purl.obolibrary.org/obo/NCBITAXON_

Do you expect this result to change in future?

**Comment by matentzn** [comment] 2020-10-29 16:07
@udp could this be solved by simply adding the baseURI to the ols ontologies.yaml config?

**Comment by henrietteharmse** [comment] 2020-10-29 16:34
The base url for NCBITaxon has not changed for as long as I can see. This is the base url that is defined for NCBITaxon: http://purl.obolibrary.org/obo/NCBITaxon_

**Comment by matentzn** [comment] 2020-10-29 16:52
Yeah but check this: https://www.ebi.ac.uk/ols/api/ontologies/NCBITaxon

Why does it say: 

![image](https://user-images.githubusercontent.com/7070631/97605899-1dae7d80-1a07-11eb-9133-3ffd2e8e90bb.png)

**Comment by henrietteharmse** [comment] 2020-10-29 17:14
Good point. I have no idea.

**Comment by udp** [comment] 2020-11-02 15:19
In the process of investigating this!

**Comment by jlchang** [comment] 2020-11-02 15:47
Thank you all for confirming that the change was not intended and investigating the issue!

**Comment by henrietteharmse** [comment] 2020-11-04 10:24
Thanks to @udp for getting to the root cause of this issue. It seemed that an error unrelated to NCBITaxon in the .yaml config caused loading of the .yaml file to fail silently. This caused the base url config for NCBITaxon the be ignored.

This is now fixed
![image](https://user-images.githubusercontent.com/32327979/98099795-e79a4f00-1e87-11eb-86ce-c305fda17a66.png)

**Closed by henrietteharmse** 2020-11-04 10:24 UTC
