### ISSUE TITLE
Mondo term at tip of hierarchy in OLS

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/OLS#302] opened 2019-11-26 09:04 UTC
Please see Mondo ticket: monarch-initiative/mondo#726

@nicolevasilevsky

**Comment by henrietteharmse** [comment] 2019-11-26 10:19
Please can someone clarify what is the problem here? According to the Mondo ticket there is an issue with the terms MONDO_0001201 and MONDO_0024253. Currently in OLS only  MONDO_0001201 is displayed and MONDO_0024253 and is *not* displayed. Is it expected that MONDO_0001201 should also not be displayed because it is deprecated? 

We are reading the .obo file, not the .owl file. Can someone please confirm how a term should be indicated as deprecated in a .obo file?

**Comment by paolaroncaglia** [comment] 2019-11-26 11:15
@henrietteharmse 
cc @cmungall and @nicolevasilevsky
Henriette, thanks for looking into this. To clarify, the issue is with MONDO_0001201 only, please see discussion from this comment down:
https://github.com/monarch-initiative/mondo/issues/726#issuecomment-557200736
MONDO_0001201 was obsoleted but it was referenced in an axiom, and that may be why it's still showing in OLS. (Note that the offending axiom was deleted, but is not released in public Mondo yet, so OLS won't catch the change until the next Mondo release.) This said, I'm afraid I won't have a chance to check the Mondo OBO file straight away - I think the matter here is not how the obsoleted MONDO_0001201 would be indicated in the OBO file (the label would be "obsolete_[term name]" and it'd have an obsolete tag = true), but whether MONDO:0001202 'prostatic cyst' would still have an axiom pointing to MONDO_0001201. Hope that helps.

**Comment by henrietteharmse** [comment] 2019-11-26 11:31
Here is the bits from the .obo file on OLS that I think that is important for this issue:
`[Term]`
`id: MONDO:0001202`
`...`
`relationship: excluded_subClassOf MONDO:0001201 {source="DOID:11133"}`

`[Term]`
`id: MONDO:0010811`
`name: benign prostatic hyperplasia (disease)`
`alt_id: MONDO:0001201`

From this I don't see how we will know that this term should not displayed.

**Comment by paolaroncaglia** [comment] 2019-11-26 11:48
@henrietteharmse thanks.
@cmungall (cc @nicolevasilevsky) Based on the sections from the .obo file above, I'm fairly confident that following the next Mondo next release, MONDO_0001201 will have disappeared from the tip of the hierarchy in OLS. The alt_id shouldn't be a problem - in your example https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0001764, the annotation does show up, in the "Term info" panel on the right, second item from the top.
I believe that this ticket may be moved to Done. Mondo may want to keep https://github.com/monarch-initiative/mondo/issues/726# open until OLS picks up the new Mondo release with the removed offending axiom, and verify that MONDO_0001201 is no longer displayed at the tip of the hierarchy. Thanks!

**Comment by cmungall** [comment] 2019-11-26 18:11
Note that although ols uses the obo version of mondo, it loads it using the owlapi which turns it into owl, a tag in the obo on the Typedef lets the owlapi know this is an annotation property not an object property:

```
    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/mondo#excluded_subClassOf">
```

**Comment by henrietteharmse** [comment] 2019-11-28 07:29
To check this out I loaded the .obo file in Protege 5.5 and stored it as .owl and it does have 
    
`<owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/mondo#excluded_subClassOf">`

but it also has this.

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/MONDO_0001201">
        <obo:IAO_0000231 rdf:resource="http://purl.obolibrary.org/obo/IAO_0000227"/>
        <obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/MONDO_0010811"/>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>

which has a deprecated annotation. I am not sure why it did not pick that up.

**Closed by henrietteharmse** 2019-11-28 07:29 UTC
