### ISSUE TITLE
Please add 'Unique short label curated by PSI-MI synonym' as special synonym field

### ISSUE THREAD

**Issue by bmeldal** [EBISPOT/OLS#65] opened 2016-03-11 09:49 UTC
In the PSI-MI ontology we often have a long list of different types of synonyms. I understand you would like to simplify these compared to the old ols but one type is crucial for curators: 'Unique short label curated by PSI-MI synonym', as this is the name that appears in the menu of our Editor.

To give you an example: 
search for 'MI:0018', 
the ontology name is 'two hybrid', 
but if you look in the old ols you see the 'unique short-label' is '2 hybrid'.
In the beta version I don't know which of all those crazy alternative names is the name that appears in my Editor...

Thanks,
Birgit

**Comment by simonjupp** [comment] 2016-03-11 09:53
This is a duplicate of #54. We've fixed this in the internal development branch and will be live in the next release.

**Comment by bmeldal** [comment] 2016-03-11 09:57
Apologies... waiting for new release :)

**Comment by simonjupp** [comment] 2016-04-21 09:57
This should be fixed now - see http://www.ebi.ac.uk/ols/beta/ontologies/mi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMI_0018

**Comment by bmeldal** [comment] 2016-04-21 10:07
Thanks! I noticed it recently.

**Closed** 2016-05-05 10:06 UTC
Labels: duplicate
