### ISSUE TITLE
NCIT ids should be NCIT:C12345 instead of NCIT_C12345

### ISSUE THREAD

**Issue by matthiaskoenig** [EBISPOT/OLS#198] opened 2018-03-28 12:22 UTC
Hi all, 
I find it very strange that the NCIT ids are not of the for `ontology:identifier` (and creates some problems in webservice queries for me).

I would expect that NCIT identifiers have the same pattern like all other ontologies. See for instance 
https://www.ebi.ac.uk/ols/api/ontologies/ncit/terms?iri=http://purl.obolibrary.org/obo/NCIT_C16353
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C16353
vs
https://www.ebi.ac.uk/ols/api/ontologies/chebi/terms?iri=http://purl.obolibrary.org/obo/CHEBI_17234
https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_17234

Best Matthias

**Comment by simonjupp** [comment] 2018-03-28 14:12
Hi Matthias,
This is a dupe of #153. The regex for obo_id expects <ontologyname>:<number> which didn't work for NCIt. I've fixed this in the 3.x-dev branch and it will be in the next release. When we reindex NCIt you'll now see the OBO ids correctly formatted. I'll close this ticket when the release goes into production. 
Cheers

**Comment by matthiaskoenig** [comment] 2018-03-28 14:28
@simonjupp Thanks. Sounds great.

**Closed** 2018-04-19 10:15 UTC

**Comment by matthiaskoenig** [comment] 2018-04-19 14:33
Thanks a lot. Is working now.
