### ISSUE TITLE
Search result doesn't resolve to a valid page

### ISSUE THREAD

**Issue by bgyori** [EBISPOT/OLS#640] opened 2022-09-28 16:32 UTC
Hello, recently I encountered multiple examples where after putting in a search term, I click on one of the results, and end up on a page saying 

> Something went wrong! Use the issue tracker or the support mail below to report any bugs or give feedback.
> 
> [Issue Tracker](https://github.com/EBISPOT/OLS/issues)
> [ols-support@ebi.ac.uk](mailto:%20ols-support@ebi.ac.uk)
> Cause unknown (no exception details available)

Here is a specific example:
![image](https://user-images.githubusercontent.com/5939016/192835746-c4950646-0c2b-43eb-8874-dba39477ed55.png)

and the page showing the error: https://www.ebi.ac.uk/ols/ontologies/cido/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCIDO_0000589

Thank you for looking into this!

**Comment by serjoshua** [comment] 2022-09-28 18:18
Hello Benjamin,

Thank you for reporting this. I already looked into it and this term is most likely one of those affected by the major data corruption we experienced last month. What our team could do is force a data update for CIDO and push it to production. We don't do regular data updates in OLS as of the moment but we will prioritize CIDO and I will keep you posted regarding any deployment.

If you encounter any term from any ontology behaving the same, please do report it as well. If the issue is data-related like this, we will try our best to prioritize an update for that ontology.

**Comment by serjoshua** [comment] 2022-10-20 09:33
Good day Benjamin,

We just finished updating CIDO in OLS. Upon revisiting the problematic API, it is resolving now. Let us know if you experience again any issues in OLS.

**Closed as completed by serjoshua** 2022-10-20 09:33 UTC
