### ISSUE TITLE
OLS has an old version of RO

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#308] opened 2019-12-10 20:38 UTC
https://www.ebi.ac.uk/ols/ontologies/ro

Says:

```
Version: 2018-10-19
Number of terms: 80
Last loaded: Mon Oct 22 06:39:09 BST 2018
```

but there is a more recent version:

```
$ curl -L -s $OBO/ro.owl | grep versionIRI
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/ro/releases/2019-09-25/ro.owl"/>
```

This can also be seen on ontobee http://www.ontobee.org/ontology/RO

**Comment by henrietteharmse** [comment] 2019-12-11 10:16
Thanks Chris for reporting. We will look into this.

**Comment by udp** [comment] 2020-04-08 15:31
I think this was caused by #330, so should be fixed when we next update prod.

**Closed** 2020-04-30 07:43 UTC
Labels: bug
